### ISSUE TITLE
configure.py fails to build docker images

### ISSUE THREAD

**Issue by mvle** [oasis-open/openc2-oif-orchestrator#49]
Trying to build the project's docker images with configure.py but it is failing. Looks like it could be an alpine version compatibility issue with velocitypack. 

Changing base/Dockerfile_alpine: FROM alpine:latest => FROM alpine:3.13 seems to work but then the logger-gui image would fail to build.

**Comment by mvle** [comment]
Just tried the development branch from above but still getting an error when building logger_gui image.

``docker.errors.BuildError: The command '/bin/sh -c apk add --no-cache git yarn && cd /tmp/gui && yarn cache clean && yarn --network-timeout 100000 || yarn --network-timeout 100000  && yarn build && mkdir -p /opt/syslog/gui && cp -r build/* /opt/syslog/gui' returned a non-zero code: 1``

**Comment by mvle** [comment]
build seems to work now

**Comment by mvle** [comment]
Not sure where to leave this issue as the ScreamBun repo doesn't have an issue tracker...

The docker-compose -f orchestrator-compose.yaml up   command doesn't work as the yaml file contains consumer-core that is not defined. 

Sorry if these problems are fixed but not yet pushed. Should I just wait until all the fixes have been pushed to OASIS before trying again?

**Comment by dlemire60** [comment]
This repo is the right spot for issues, whether for development or final release versions.

**Comment by ScreamBun** [comment]
There is a new push on the [development branch](https://github.com/ScreamBun/openc2-oif-orchestrator). Building and `docker-compose ... up` all appear to be functional.
It appears the reference to 'consumer-core' we missed in removal during testing of another portion of the Orchestrator.

**Comment by mvle** [comment]
Works. Thanks!
